# Generated by Django 4.0.3 on 2022-03-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scanedtext',
            new_name='ScanedTextImage',
        ),
    ]
