# Generated by Django 4.0.3 on 2022-03-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_scanedtext_scanedtextimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanedtextimage',
            name='name',
        ),
    ]
