# Generated by Django 4.0.5 on 2022-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_scanedtextimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('translate_to', models.CharField(choices=[('Spanish', 'Spanish'), ('French', 'French')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
