# Generated by Django 4.0.5 on 2022-06-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_translatetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatetext',
            name='translate_to',
            field=models.CharField(choices=[('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German')], max_length=100),
        ),
    ]
