# Generated by Django 4.0.5 on 2022-06-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_scanedtextimage_scanned_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatetext',
            name='translate_to',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('fr', 'French'), ('gm', 'German')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translatetext',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
