# Generated by Django 4.0.5 on 2022-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_translatetext_translate_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='translatetext',
            name='translate_to',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('af', 'Twi'), ('ha', 'Hausa')], max_length=100, null=True),
        ),
    ]
